# Input/output configuration
# input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/feature_store_endcaps_all
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/1_pt_cut_endcaps_unweighted_augmented
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/1_pt_cut_endcaps_unweighted
project: CodaEmbeddingStudy
overwrite: True

# Dataset parameters
pt_min: 1
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [100, 10, 1] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
emb_hidden: 256
nb_layer: 4
emb_dim: 12
weight: 2
randomisation: 2
r_train: 0.3
r_val: 0.3
r_test: 0.1
knn: 50
warmup: 500
margin: 0.3
lr: 0.001
factor: 0.3
patience: 20
regime: [rp, hnm, pid, norm]
max_epochs: 10

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data