# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/toy_datasets/case_A2
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/gnn_processed/0_pt_cut_endcaps_weighted
project: CodaGNNStudy
edge_cut: 0.5

# Dataset parameters
pt_min: 1
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [5000, 100, 1] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
hidden: 64
emb_dim: 8
n_graph_iters: 6
nb_node_layer: 3
nb_edge_layer: 3
nb_emb_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
edge_loss_only: True
emb_loss_only: False

r_train: 1
r_val: 1
r_test: 1
randomisation: 1
weight: 1
knn: 20
margin: 1
warmup: 100
lr: 0.001
factor: 0.3
patience: 120
regime: [pid, balanced]
max_epochs: 300
slack_alert: False

# Post-processing
callbacks: #[GNNInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
