# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/1_pt_cut_endcaps_unweighted_augmented
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/gnn_processed/0_pt_cut_endcaps_weighted
project: CodaGNNStudy
edge_cut: 0.5

# Dataset parameters
pt_min: 1
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [500, 20, 20] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
hidden: 64
emb_dim: 16
n_graph_iters: 6
nb_node_layer: 2
nb_edge_layer: 2
nb_emb_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
edge_loss_only: False
emb_loss_only: False

r_train: 1
r_val: 1
r_test: 1
randomisation: 1
weight: 2
knn: 20
margin: 1
warmup: 400
lr: 0.001
factor: 0.3
patience: 10
regime: [rp, hnm, pid]
max_epochs: 20
slack_alert: False

# Post-processing
callbacks: #[GNNInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
