# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml/train_all
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml_processed/0.5_pt_cut_endcaps/all_events
n_files: 8600

selection:
    pt_min: 0.5
    endcaps: True
    noise: False
    adjacent: True