# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/1_pt_cut_endcaps_unweighted_augmented
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/1_pt_cut_endcaps_unweighted_augmented
project: CodaEmbeddingStudy
overwrite: True

# Dataset parameters
pt_min: 1
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 20, 20] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
emb_hidden: 64
filter_hidden: 64
nb_embedding_layers: 4
nb_filter_layers: 4
emb_dim: 8
weight: 2
randomisation: 1
r_train: 1
r_val: 1
r_test: 1
filter_cut: 0.5
knn: 40
warmup: 300
margin: 1
lr: 0.001
factor: 0.3
patience: 8
regime: [rp, hnm, pid, noisy]
max_epochs: 10

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data