# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/embedding_processed/1_pt_cut_endcaps_unweighted
output_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml-codalab/gnn_processed/0_pt_cut_endcaps_weighted
project: CodaGNNStudy
edge_cut: 0.5

# Dataset parameters
pt_min: 1
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 20, 20] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 3
hidden: 64
n_graph_iters: 1
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 12
delta_eta: 1.2
warmup: 300
lr: 0.001
factor: 0.3
patience: 40
regime: [pid, eta_slice]
max_epochs: 90
slack_alert: False
n_edges: 2900

# Post-processing
callbacks: #[GNNInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data
